### ISSUE TITLE
Redundant RAFO in $FMO group causes error if no bonds are cut.

### ISSUE THREAD

**Issue by andersx** [FragIt/fragit-main#15]
As title says. E.g. if you use Fragit to fragment a water cluster, and therefore no bonds are cut, the "RAFO(1)=1,1,1" line is still in the $FMO group, which in turn confuses GAMESS and yields the following message:

    "FMO/AFO requires some orbital localisation in $CONTRL LOCAL."

Thank you for making fragit! It is an awesome tool!

**Comment by andersx** [comment]
The following input should produce the error:

    fragit --use-config myconf.ini minimum.xyz




    18
    
    O         -2.3460000000    -0.5959444444    -1.0982777778
    H         -1.4260000000    -0.7659444444    -0.8402777778
    C         -3.1590000000    -1.1199444444    -0.0712777778
    H         -4.1940000000    -0.9179444444    -0.3352777778
    H         -3.0450000000    -2.2009444444     0.0427222222
    H         -2.9620000000    -0.6539444444     0.8987222222
    C         -0.1640000000     1.5240555556     0.3657222222
    H          0.3430000000     2.4860555556     0.3307222222
    H         -0.5740000000     1.3780555556     1.3637222222
    H         -0.9930000000     1.5150555556    -0.3352777778
    C          0.7520000000     0.3690555556     0.0497222222
    O          0.3280000000    -0.7509444444    -0.2352777778
    N          2.0780000000     0.6310555556     0.1097222222
    H          2.3760000000     1.5410555556     0.4067222222
    C          3.0610000000    -0.4089444444    -0.1132777778
    H          2.7040000000    -1.0599444444    -0.9052777778
    H          4.0010000000     0.0440555556    -0.4122777778
    H          3.2200000000    -1.0139444444     0.7787222222

**Comment by andersx** [comment]
Temporary fix is just to comment the RAFO line out :dancers:

**Comment by cstein** [comment]
Could you also please supply `myconf.ini`? :)

Much appreciated!

**Comment by andersx** [comment]
myconf.ini

    [mergepatterns]
    glycine = 
    
    [fragmentation]
    chargemodel = MMFF94
    combinefragments = 
    writer = GAMESS-FMO
    groupcount = 1
    maxfragsize = 100
    
    [explicitfragmentpairs]
    pairs = 
    
    [mfcc]
    order = 0
    
    [fragmentpatterns]
    a-d-pyranose = [$(C1C(CO)OC(O)C(O)C1(O))][$(OC1C(O)C(O)CC(CO)O1)]
    peptide = [$(CN)][$(C(=O)NCC(=O))]
    dnabackbone = [$(CCOP)][$(CC1OCCC1)]
    
    [qmmm]
    includecovalent = False
    includeallwithin = 0.0
    hbonddistancemin = 2.5
    hbondangle = 110.0
    hbonddistancemax = 3.9
    includehbondacceptors = False
    includehbonddonors = False
    
    [protectpatterns]
    nterminal = [$([NH2]),$([NH3])]CC(=O)[$(NCC=O)]
    
    [explicitprotectatoms]
    atomids = 
    
    [output]
    freezebackbone = False
    verbose = True
    useatomnames = False
    buffer = 0.0
    writejmol = False
    boundaries = 
    writepymol = True
    centralfragment = 0
    active = 0.0
